[tox]
minversion = 4.0
envlist = tests, mypy, ruff
isolated_build = True

[testenv]
setenv = PYTHONPATH = .
deps =
    pytest
    fastapi
    uvicorn[standard]
    pydantic
    python-dotenv
    google-cloud-firestore
    google-generativeai
    requests
    numpy
    mypy
    ruff

[testenv:tests]
description = Run pytest
commands =
    pytest backend/tests

[testenv:mypy]
description = Run mypy
commands =
    mypy -p backend

[testenv:ruff]
description = Run ruff
commands =
    ruff check backend
